import { createControlPanel } from '../../lib/ControlPanel/index.mjs'
import Particle from './FlowParticle.mjs'

export default (p, metadata) =>
  createControlPanel({
    p,
    id: metadata.name,
    compact: true,
    controls: [
      {
        type: 'Range',
        name: 'count',
        value: 100,
        min: 5,
        max: 10_000,
        step: 5,
      },
      {
        type: 'Range',
        name: 'backgroundAlpha',
        display: 'bgAlpha',
        value: 0.62,
        min: 0,
        max: 1,
        step: 0.001,
      },
      {
        type: 'Range',
        name: 'history',
        value: 4,
        min: 1,
        max: 100,
        step: 1,
      },
      {
        type: 'Range',
        name: 'noiseScale',
        value: 0.0001,
        min: 0.0001,
        max: 0.05,
        step: 0.0001,
      },
      {
        type: 'Range',
        name: 'forceMagnitude',
        display: 'forceMag',
        value: 0.1,
        min: 0.01,
        max: 1,
        step: 0.001,
      },
      {
        type: 'Range',
        name: 'zOffsetMultiplier',
        display: 'zOffs',
        value: 0.01,
        min: 0.001,
        max: 1,
        step: 0.001,
      },
      {
        type: 'Range',
        name: 'angleOffset',
        value: 0,
        min: 0,
        max: 360,
        step: 1,
      },
      {
        type: 'Range',
        name: 'blackHoleStrength',
        display: 'bhStrength',
        value: 1000,
        min: 1,
        max: 10_000,
        step: 1,
      },
      {
        type: 'Range',
        name: 'attractorStrength',
        display: 'attrStrength',
        value: 1000,
        min: 0.1,
        max: 100,
        step: 0.1,
      },
      {
        type: 'Select',
        name: 'edgeMode',
        value: 'wrap',
        options: Object.values(Particle.EdgeMode),
      },
      {
        type: 'Select',
        name: 'forceMode',
        value: 'grid',
        options: [
          'grid',
          'algorithmic',
          'combinedAdditive',
          'combinedAveraged',
        ],
      },
      {
        type: 'Checkbox',
        name: 'showParticles',
        value: true,
      },
      {
        type: 'Checkbox',
        name: 'applyRandomForce',
        value: false,
      },
      {
        type: 'Checkbox',
        name: 'showSwatches',
        value: false,
      },
      {
        type: 'Checkbox',
        name: 'showField',
        value: false,
      },
      {
        type: 'Checkbox',
        name: 'showObstacles',
        value: false,
      },
      {
        type: 'Checkbox',
        name: 'showBlackHole',
        value: false,
      },
      {
        type: 'Checkbox',
        name: 'showAttractors',
        value: false,
      },
    ],
  })
